spring:
  datasource:
    url: jdbc:mysql://localhost:3306/barber-shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true
    validate-on-migrate: true